### ISSUE TITLE
license

### ISSUE THREAD

**Issue by dvs1** [mdoege/3NewsFeed#1]
The only information I see about a license is
`__license__   = "GPL"` in newsfeed.py

I recommened adding:

```
<one line to give the program's name and a brief idea of what it does.>
    Copyright (C) <year>  <name of author>

    This program is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with this program.  If not, see <http://www.gnu.org/licenses/>.
```

and the file https://www.gnu.org/licenses/gpl-3.0.txt

https://www.gnu.org/licenses/gpl-3.0.en.html
https://www.gnu.org/licenses/gpl-violation.html

**Comment by mdoege** [comment]
The GPL license is linked to from the project's web page. No need to include it in the repo IMO.

**Comment by dvs1** [comment]
People can obtain the source without ever visiting your website;
and what your website links to is irrelevant,
because you can change that (it's not bound to a static source package).

Including the license with the source is fundamental for GPL.

> You should have received a copy of the GNU General Public License along with this program.

And

> Does the distribution contain a copy of the License?

-> https://www.gnu.org/licenses/gpl-violation.html

Legally speaking I don't think this repository is even licensed.
"GPL" doesn't specify an actual license.
Minimally you would need to put "GNU General Public License";
and then that allows for people to choose GPLv1,
which isn't really desirable.

**Comment by mdoege** [comment]
Well, if you feel so strongly about this issue you should simply put all required changes in a pull request and I will merge it...
