### ISSUE TITLE
starting the program with `__main__.py`

### ISSUE THREAD

**Issue by dvs1** [mdoege/3NewsFeed#3]
What do you think about replacing Start_NewsFeed.py and newsfeed (executable)
with `__main__.py`?

https://stackoverflow.com/questions/4042905/what-is-main-py

**Comment by mdoege** [comment]
Interesting, but I think this should be added as a third option. Start_NewsFeed.py is mainly for Windows (starting from Explorer), newsfeed is for Linux/macOS. This __main__.py seems to be a bit more obscure, and I don't think it works for starting from Windows Explorer.

**Comment by mdoege** [comment]
https://github.com/mdoege/3NewsFeed/commit/0480643215b8a089720ed7ce5b7b27c7f783754b
